[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[dev]
  port = 8080
  publish = "."
  functions = "netlify/functions"

# Redirect API calls to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Environment variables for production
# Set these in Netlify dashboard: Site settings > Environment variables
# NEON_DATABASE_URL = "your-neon-connection-string"